### PR TITLE
Permutations logic changed to cover all words of line

### PR DESCRIPTION
**Pull request by nishantgupta91-zz**

### CODE REVIEW

**Comment by zheden** [comment]
Hi, I see you reverted some of my changes:
1. You load each word again multiple times. If it is in 100 permutations, for each permutation you read it once more
2. I added MAX_NUM_WORDS_PERMUTATIONS, because we dont actually want factorial of num of words(will be too much and yet we dont have enough space on our lad compuetrs). You removed it
3. I used MAX_LINES_TO_TRAIN , MAX_LINES_TO_TEST, because we have two datasets, for each some num of lines. Why did you add MAX_LINES again?

I did not run this code yet, I dont have access now to lab computer, but looks for me that there will be duplicates. (Because you append wordsSet after max width is reached and just cut what is left) Did you try to take really small max_width (~size of 1 word) and check if there will be no duplicates in images?

**Comment by nishantgupta91-zz** [comment]
Hi.. I think we can discuss these issues on Skype. Just let me know whenever you're available tomorrow. I have done a bit of testing and I think there should be no duplicates here. We can discuss it tomorrow..

**Comment by zheden** [comment]
Sure, my skype is zheden3
I will be busy today from 1 to 2, other time is fine

**Comment by zheden** [comment]
Hi, I run it, they don't duplicate, that's fine)

**Pull request merged**
